### PR TITLE
WIP: switch to ECR from dockerhub; broken...

### PR DESCRIPTION
**Pull request by lily-mayfield**
Works EXCEPT I get an error when trying to run a job about an auth
handler and I think this may have something to do with awscli being
installed twice, once in virtualenv another time already pre-installed
from AMI (I think) or a specific version Boto3 wants...

### CODE REVIEW

**Comment by lily-mayfield** [comment]
I have no idea why changing those lines results in `NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials`

**Comment by lily-mayfield** [comment]
okay so here's the unchanged `master`:

```
18/01/10 15:18:47 INFO anyconfig.backends: ConfigObj module is not available. Disabled its support.
18/01/10 15:18:47 INFO anyconfig.backends: msgpack module is not available. Disabled MessagePack support.
18/01/10 15:18:47 INFO anyconfig.backends: toml module is not available. Disabled TOML support.
18/01/10 15:18:47 INFO anyconfig.backends: bson module in pymongo package is not available. Disabled BSON support.
18/01/10 15:18:47 INFO anyconfig: Loading: /code/osp_pipeline/core/osp.yml
18/01/10 15:18:47 INFO anyconfig: Loading: /etc/osp/osp.yml
18/01/10 15:18:47 INFO anyconfig: Loading: /tmp/osp.lock.yml
```

**Comment by wearpants** [comment]
Will look in detail, but that message happens when  boto can't find your
AWS keys... Should "just work"  but maybe need to bake them in to
~/.boto/config or envvar?

**Comment by lily-mayfield** [comment]
It turned out to be due to this bizarre issue with the image that is now fixed.

**Pull request merged**
