### PR TITLE
Tweak model schemas with md5sums and 'source_anchor'

### PR DESCRIPTION
**Pull request by jodizzle**
Two small additions:

- An md5sum-generating utility, and corresponding md5sum fields for all models.  In the case of the raw document models, the md5sum is based off of the raw binary `data` field; in the case of `DocumentText`, it's based off of the extracted `text` field.  Having both types of md5sums available may end up being superfluous, but I don't think there's much harm in trying both out.  Regardless, md5sums should be helpful for any sort of dedupe process.
- Inclusion of 'source_anchor' in the unified `Document` model, which it just inherits from each `V2CorpusDocument`.  Access to this metadata is currently necessary/very helpful for running predictions with the classifiers.

There were a lot of tweaks and changes I made to the tests and test-helpers, so review would be appreciated.

Questions:
- Is protection against `None` necessary in the `from_source` methods?  I could just add protection to `get_md5` directly, but I wasn't sure if that was best.  Currently, I only check against `None` for `V2CorpusDocument` and `DocumentText` because `warc.doc_data()` and `osp_text_extractor.bytes_to_text()` can both explicitly return `None` values.
- Should the 'md5' field in `DocumentText` be named something slightly different so as to be distinct from the 'md5's in the raw document models?

### CODE REVIEW

**Comment by wearpants** [comment]
Yes I'd do data_md5 and text_md5. Don't understand the other question

**Comment by wearpants** [comment]
Oic, get_md5 looks fine, I'd handle None in the sources

**Comment by lily-mayfield** [comment]
I scanned over it :eyes: and it looks really good to me; great job @jodizzle!

**Comment by jodizzle** [comment]
Alright, I distinguished `data_md5` and `text_md5`, and made the checks against `None` a little clearer.  I'll merge now.

Also, sidenote: I chose to use `hash.hexdigest()` instead of `hash.digest()` (hexadecimal string vs. any-type-of-bytes string) for storing the md5sums.  I figured this was better, though I think the distinction is probably pretty arbitrary for our purposes.

**Pull request merged**
