### PR TITLE
Institutions finale tests

### PR DESCRIPTION
**Pull request by wearpants**
finally done!

### CODE REVIEW

**Comment by davidmcclure** [comment]
This looks great. I pushed a couple of small changes:

- Reverted the schema consistency checks in the base Model method. I like this idea a lot, but unfortunately it breaks any model that uses `nullable=False`. The problem is that Spark, when it actually writes out the schema into the Parquet, changes all fields to be `nullable=True`, for some kind of compatibility reason. (See [here](https://github.com/apache/spark/blob/master/docs/sql-programming-guide.md#parquet-files).) Which means, when we then re-load the dataframe, the schema check fails since the Parquet thinks everything is nullable, but the declared schema thinks some fields aren't.

  One solution would be to just never use `nullable=True` in our schemas, but that's a loss, since, at the application level, Spark does enforce the constraint when we do `spark.createDataFrame(...)`. So we get an assurance that the non-nullable fields are populated at write-time, which is valuable.

- In the institutions tests, moved the three fixtures into a `conftest.py` file, which just means that we don't have to explicitly import that `df` fixture, which was causing flake8 warnings.

- Instead of using a separate `spark_uuid4()` helper function defined in `institutions.utils`, I moved this into the body of `Institutions.build()`. This was because, for some reason, the call to udf() spins up a SparkContext, or something, which then conflicts with the pytest-managed session when anything is imported from `utils` in the tests.

@wearpants Let me know if these changes look good, and let's merge. Thanks!

**Comment by wearpants** [comment]
All looks fine but I might rename 'df' to institutions_df if you relocated
it since it's not the only data frame well have

**Comment by davidmcclure** [comment]
I put it in a `conftest.py` that's specific to the institutions tests, so it's only in scope under that module, not the whole suite. This is effectively the same as just importing the `df` variable from one test file to another, like before, so I think it's fine to leave it as `df`.

**Comment by wearpants** [comment]
sorry, path was folded up... looks great :-)

**Pull request merged**
