### PR TITLE
Store raw document bytes

### PR DESCRIPTION
**Pull request by davidmcclure**
This refactors the corpus models / jobs so that we store the raw bytes for the documents. Before, we were just storing the extracted plain text for documents. Eg, when we ingested WARCs from the scraper, text extraction was done immediately, and the raw bytes were thrown out.

There are a variety of reasons that we might want the original docs, I've realized. For example, when extracting dates for the syllabi - PDFs often include metadata in the file header about when the document was created or modified. Or, in the (more distant) future - when extracting text assignments, we could conceivably hook on to formatting features in the text to improve accuracy, things like whether or not words in a candidate title are italicized. Which could theoretically be recovered from the raw document, but which get lost in the plain text.

### CODE REVIEW

**Comment by wearpants** [comment]
`Documents` no longer have a `text` field? I'm pretty sure this was in use elsewhere in the codebase (here at least: https://github.com/opensyllabus/osp-pipeline/blob/master/osp_pipeline/institutions/matcher.py#L224)

**Comment by davidmcclure** [comment]
That's right, thanks, I forgot that the institution matching is already using the text to find emails.

I forgot to say in the PR - text certainly isn't disappearing, I'm just moving it to a separate dataframe. So, in the same way that, eg, the classifier job will write out the classifications as a separate schema of `(document id, classification)`, I'm going to add an `extract_text` job that writes the text and inferred mime type into a adjacent table. Something like:

```python
class DocumentText(metaclass=ModelMeta):

    key = 'document_texts'

    schema = T.StructType([
        T.StructField('document_id', T.StringType(), nullable=False),
        T.StructField('mime_type', T.StringType()),
        T.StructField('text', T.StringType()),
    ])
```

So, that way the raw document bytes are stored in Document, and we can join on DocumentText to get the text.

I was going to do that as a separate PR, but I'll do ahead and do this here, and update the institution matching. I'll also see if I can write an integration test to check the interaction between the two modules.

**Comment by davidmcclure** [comment]
Hey @wearpants,

Ok, I just pushed the changes that make this work with the institution matching, along with a little bit of framework-y code for structuring the joins.

To recap - instead of storing document metadata + text on in a single table, we now just store the raw document bytes in `Document`:

```python
class Document(metaclass=ModelMeta):
    """Unified data model (UDM) for the various raw corpus sources.
    """

    s3_key = 'documents'

    schema = T.StructType([
        T.StructField('id', T.StringType(), nullable=False),
        T.StructField('corpus', T.StringType(), nullable=False),
        T.StructField('corpus_id', T.StringType(), nullable=False),
        T.StructField('url', T.StringType()),
        T.StructField('source_url', T.StringType()),
        T.StructField('retrieved', T.TimestampType()),
        T.StructField('data', T.BinaryType()),
    ])
```

And, the mime type and text are extracted to a separate table that links on the document ids:

```python
class DocumentText(metaclass=ModelMeta):

    s3_key = 'document_texts'

    schema = T.StructType([
        T.StructField('document_id', T.StringType(), nullable=False),
        T.StructField('mime_type', T.StringType()),
        T.StructField('text', T.StringType()),
    ])
```

This pattern having an "entity" table, annotated by "metadata" tables, will come up lots - eg, when we write out results for deduping / classification.

So, with institutions - for the matching, we use the document id, URL, source URL, and plain text, which are now broken across two tables, so we need a join. In the tests, it's also nice to be able to easily mock one of the rows that would get produced by the join. I also wanted some way to explicitly represent the structure of the joins, similar to how to organize the models. To do this, I added a `JoinRow` construct, which is very similar to the `Model` class we use. Basically, a join row just defines a set of columns that will be present in the joined row, and, in a `build_df` classmethod, implements the join itself and selects out the needed columns. For institutions:

```python
from osp_pipeline.core.joins import JoinRowMeta

class MatchDocument(metaclass=JoinRowMeta):

    fields = ['id', 'url', 'source_url', 'text']

    @classmethod
    def build_df(cls, docs, texts):
        """Join document URLs + extracted text.

        Args:
            docs (DataFrame of Document)
            texts (DataFrame of DocumentText)
        """
        return (docs
                .join(texts, docs.id == texts.document_id)
                .select(cls.fields))
```

And then, in the job itself, we just load up the model DFs, pass them to `.build_rdd()` classmethod on the join row, which executes the join and wraps each row as a `MatchDocument`:

```python
docs = Document.read(spark)
texts = DocumentText.read(spark)

match_docs = MatchDocument.build_rdd(docs, texts)
```

The other nice thing about this is that it makes it easy to write domain logic for the joined rows - eg, we could just start adding row-level methods to `MatchDocument`, just like a regular model.

All tests are passing on this, let me know what you think.

**Comment by wearpants** [comment]
Hmm... so there's nothing really specific to *joining* about `JoinRow` / `JoinRowMeta` - it's a way of representing _any_ computed dataframe... I was kind of expecting it to be declarative, instead of needing to implement `build_df` yourself:

```
from osp_pipeline.core.joins import JoinRowMeta

class MatchDocument(metaclass=JoinRowMeta):
    fields = ['id', 'url', 'source_url', 'text']
    models = (Document, DocumentText)
    on = ('id', 'document_id')
```

And having the base class implement the join (using same logic as you did).

Not entirely sure what the present class gets us above and beyond standalone implementations of `build_df()`? I think I'm missing something...

**Comment by davidmcclure** [comment]
Yeah, you're right, this is really more convention than code at this point. The immediate impetus was just to get the institution code working again, specifically the `TextDomain` class, which wraps around a `Document` row, and uses the old `text` fields. Since `text` got broken off into a separate table, though, it doesn't work to pass a raw `Document` anymore. This can be fixed in the job itself just by doing the join and mapping on the joined RDD, but there was also the question of how to handle this in the tests, where it's necessary (or at least much much easier) to just spin up testing `Document` rows and pass them into the code under test, like you do here:

https://github.com/opensyllabus/osp-pipeline/blob/master/tests/osp_pipeline/institutions/test_matcher.py#L32

So `MatchDocument` really just provides an easy way to mock one of the joined rows, like here:

https://github.com/opensyllabus/osp-pipeline/blob/store-bytes/tests/osp_pipeline/institutions/test_matcher.py#L32

And gives (very) loose structure to the code that produces the real join in the jobs.

But yeah, I really like this idea:

```python
class MatchDocument(metaclass=JoinRowMeta):
    fields = ['id', 'url', 'source_url', 'text']
    models = (Document, DocumentText)
    on = ('id', 'document_id')
```

Only thought that pops to mind - will we ever need to more complex joins? Eg, 3+ tables, etc? I'll play with this later today and update here.

Thanks.

**Comment by wearpants** [comment]
> Only thought that pops to mind - will we ever need to more complex joins?
Eg, 3+ tables, etc?

Right, at some point this generalizes to functions taking and returning
dataframes...

**Comment by davidmcclure** [comment]
@wearpants, want to go ahead and merge this as-is, for now, and loop back later to the question of how structured the API should be for the joins?

**Pull request merged**
